### ISSUE TITLE
Get an event when a sonos device is not available anymore

### ISSUE THREAD

**Issue by tboudri** [bencevans/node-sonos#484] opened 2020-08-18 09:35 UTC
The packages has a discovery functie that notifies me when a Sonos device becomes available. But there is no event available that notifies me when a device is not available anymore

The Discovery Search could be extended with a mechanism that, when a device does not respond within a few searches it is assumed to be turned off

**Comment by pascalopitz** [comment] 2020-08-18 09:40
You can do 

```
import { Listener } from 'sonos';

Listener.on('ZonesChanged', (zones) => {})
```

**Comment by tboudri** [comment] 2020-08-18 10:45
Thank you for your super quick response.
ZonesChanged is not useful for this. This event is not fired when a device is not available anymore.
This event gets fired with useful information on app startup. When devices are added, the event gets fired with the zones param = undefined. But no event when a device is not available anymore

**Comment by pascalopitz** [comment] 2020-08-18 11:06
Weird. Just tested this, and I can confirm ... no event comes through immediately when a zone player gets removed.
The weird thing is ... it also doesn't come through on the Android native app. When that updates, I can actually see a ZonesChanged event come through. It takes a considerable while though.

**Comment by svrooij** [comment] 2020-08-27 10:12
To check this, we would need to create something that would actively be sending a message to each speaker to see if it's still online.

**Comment by pascalopitz** [comment] 2020-08-27 10:14
Maybe could we open a dgram socket and when when it does and you cannot
reconnect it it fires the event?

**Comment by tboudri** [comment] 2020-08-27 10:32
I have a quick&dirty solution. The DeviceDiscovery polls constantly for new Devices. I have modified this  so that at each polling interval it checks if one or more 'known' devices are not reacting anymore. If a device does not react within 5 polling iterations it is considered 'dead'. Now my app can react on this but node-sonos still thinks the device is available. Thats why i sometimes get a timeout error when calling getAllGroups on a device that is still available but one or more other devices are not discoverable anymore

**Comment by svrooij** [comment] 2020-08-27 17:51
Why not just do polling every 1 minute for the volume or something basic. Like status page, preferably something small

**Comment by svrooij** [comment] 2020-11-02 22:19
I'm closing this issue for now, but if someone feels like creating a PR for this feature you can always re-open.

**Closed by svrooij** 2020-11-02 22:19 UTC
Labels: feature, need-info

**Comment by hklages** [comment] 2020-12-27 18:39
Instead of polling for volume etc you can just send an html request 
`http://192.168.178.37:1400/info`
with a time out of milliseconds (adjusted to your network).

**Comment by tboudri** [comment] 2020-12-28 07:27
Although this post was already closed i decided to post my solution. As i mentioned, there is a DeviceDiscovery class that polls via uPnp for devices. I have modified this class so that when a device comes online it is registered in a list inside the DeviceDiscovery.  Now every times DeviceDiscovery polls for devices it will also check if devices in that list still respond. If a device does not respond for some time an event is fired. This is very efficient because polling is already done. There is no need for extra polling. And it can react very quickly when devices are not online anymore

**Comment by hklages** [comment] 2020-12-28 07:40
Thanks for that information. Very smart solution. 

I will check whether that fits in my program. Right now I only do device discovery once after a system shutdown. During run time I just throw the actions to the (static) IP address and act on the error if unreachable. That's good for system load but unreachable speakers can cause problems.

**Comment by svrooij** [comment] 2020-12-28 07:42
The device Discovery isn't meant to be used all the time. Since it uses since it uses udp broadcast it may cause noise on your network.

I think starting an interval and polling to a /info endpoint is the way to go.
